// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcstoreResultModel.Data;

#nullable disable

namespace MindSpringsTest.Migrations
{
    [DbContext(typeof(MvcstoreResultModelContext))]
    partial class MvcstoreResultModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("MindSpringsTest.Models.storeResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextEntered")
                        .HasColumnType("TEXT");

                    b.Property<string>("translatedText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("storeResultModel");
                });
#pragma warning restore 612, 618
        }
    }
}
